# -*- coding: utf-8 -*-
"""LOGISTIC REGRESSION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WQZH5u6XwP7Df79bYvkZSfN0fscCSSK5
"""

#!pip install streamlit

import joblib
joblib.dump(model, 'logistic_model.pkl')

import streamlit as st
import joblib
import numpy as np

model = joblib.load("logistic_model.pkl")

st.title("Titanic Survival Prediction")

pclass = st.selectbox("Passenger Class (Pclass)", [1, 2, 3])
sex = st.selectbox("Sex", ['male', 'female'])
age = st.slider("Age", 0, 100, 25)
sibsp = st.number_input("Siblings/Spouses Aboard (SibSp)", 0, 10, 0)
parch = st.number_input("Parents/Children Aboard (Parch)", 0, 10, 0)
fare = st.number_input("Fare", 0.0, 500.0, 50.0)
embarked = st.selectbox("Port of Embarkation", ['C', 'Q', 'S'])

# Encoding
sex = 0 if sex == 'male' else 1
embarked_dict = {'C': 0, 'Q': 1, 'S': 2}
embarked = embarked_dict[embarked]

input_data = np.array([[pclass, sex, age, sibsp, parch, fare, embarked]])
prediction = model.predict(input_data)

if st.button("Predict"):
    st.success("Survived" if prediction[0] == 1 else "Did not survive")

